trigger:
- master

variables:
  solution: 'MSBuildPrediction.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildOnWindows
  displayName: "Build and test on Windows"
  pool:
    name: 'Hosted Windows 2019 with VS2019'
  steps:
  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildVersion: '16.0'
- job: BuildOnLinux
  displayName: "Build and test on Linux"
  pool:
    name: 'Hosted Ubuntu 1604'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'MSBuildPrediction.sln'
